import datetime
import os
import sys

import pandas as pd


if getattr(snakemake, "log", None):
    log_path = str(snakemake.log[0])
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    log_handle = open(log_path, "w")
    sys.stdout = log_handle
    sys.stderr = log_handle


def strip_fastq_name(path):
    name = os.path.basename(path)
    for suffix in (".fastq.gz", ".fq.gz", ".fastq", ".fq"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name


def format_percent(value):
    if pd.isna(value):
        return ""
    return f"{float(value):.2f}%"


cutadapt_path = snakemake.input.get("cutadapt", None)
seqkit_pre = snakemake.input.seqkit_pre
seqkit_post = snakemake.input.seqkit_post

df_pre = pd.read_table(seqkit_pre)
df_post = pd.read_table(seqkit_post)

df_pre["sample"] = df_pre["file"].apply(strip_fastq_name)
df_post["sample"] = df_post["file"].apply(
    lambda x: os.path.basename(x)
    .replace("-nanofilt.fastq", "")
    .replace("-scrubbed.fastq", "")
)

df_pre = df_pre[["sample", "num_seqs", "sum_len", "min_len", "avg_len", "max_len"]]
df_post = df_post[["sample", "num_seqs", "sum_len", "min_len", "avg_len", "max_len"]]

df_pre.columns = ["sample", "raw_reads", "raw_sum_len", "raw_min_len", "raw_avg_len", "raw_max_len"]
df_post.columns = ["sample", "filtered_reads", "filtered_sum_len", "filtered_min_len", "filtered_avg_len", "filtered_max_len"]

df = pd.merge(df_pre, df_post, on="sample", how="outer")
df["filtered_reads_pct"] = (df["filtered_reads"] / df["raw_reads"]) * 100

has_cutadapt = cutadapt_path and os.path.exists(cutadapt_path)
if has_cutadapt:
    df_cutadapt = pd.read_table(cutadapt_path)
    df_cutadapt.columns = ["sample", "reads_retained_pct", "bps_retained_pct"]
    df_cutadapt["reads_retained_pct"] = df_cutadapt["reads_retained_pct"].str.replace("%", "", regex=False).astype(float)
    df_cutadapt["bps_retained_pct"] = df_cutadapt["bps_retained_pct"].str.replace("%", "", regex=False).astype(float)
    df = pd.merge(df, df_cutadapt, on="sample", how="left")

display = pd.DataFrame()
display["sample"] = df["sample"]
display["raw_reads"] = df["raw_reads"]
if has_cutadapt:
    display["cutadapt_reads_retained"] = df["reads_retained_pct"].map(format_percent)
    display["cutadapt_bases_retained"] = df["bps_retained_pct"].map(format_percent)
display["filtered_reads"] = df.apply(
    lambda row: (
        f"{int(row['filtered_reads'])} ({row['filtered_reads_pct']:.2f}%)"
        if pd.notna(row["filtered_reads"]) and pd.notna(row["filtered_reads_pct"])
        else ""
    ),
    axis=1,
)
display["filtered_avg_len"] = df["filtered_avg_len"]
display["filtered_min_len"] = df["filtered_min_len"]
display["filtered_max_len"] = df["filtered_max_len"]

report_table_tsv = display.to_csv(sep="\t", index=False)

taxonomy_info = {
    "silva": ("Silva", "138.1"),
    "rdp": ("RDP", "11.5"),
    "emu": ("EMU", "3.0"),
    "pr2": ("PR2", "5.1.1"),
}
db_name, version = taxonomy_info.get(snakemake.params.tax_db, ("Unknown", "N/A"))

start_formatted = datetime.datetime.fromisoformat(snakemake.params.start).strftime("%Y-%m-%d %H:%M:%S")
end_formatted = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

report_lines = [
    "# Report file",
    f"Analysis started: {start_formatted}",
    f"Analysis ended: {end_formatted}",
    "",
]

if snakemake.params.to_cutadapt:
    report_lines.extend([
        "## Primer Trimming",
        f"- Forward primer: `{snakemake.params.forward_p}`",
        f"- Reverse primer: `{snakemake.params.reverse_p}`",
        f"- Reverse-complement reverse primer used in cutadapt: `{snakemake.params.RC_RVS}`",
        "- Cutadapt runs with `--revcomp`, so both strand orientations are considered on single long reads.",
        "",
    ])

report_lines.extend([
    "## NanoFilt Parameters",
    f"- Minimum length: `{snakemake.params.nl_min_len}`",
    f"- Maximum length: `{snakemake.params.nl_max_len}`",
    f"- Minimum average quality: `{snakemake.params.nl_min_qual}`",
    "",
    "## EMU Parameters",
    f"- Minimum relative abundance: `{snakemake.params.emu_min_ab}`",
    f"- Database: `{db_name}`",
    f"- Version: `{version}`",
])

if snakemake.params.trimming_method:
    report_lines.extend([
        "",
        "## Adapter Trimming",
        f"- Method: `{snakemake.params.trimming_method}`",
    ])

report_lines.extend([
    "",
    "## Summary Table",
    report_table_tsv,
    "",
    "## Citation",
    "Generated by AmpWrap",
    "",
    "https://github.com/LDoni/AmpWrap",
])

with open(snakemake.output.report, "w") as handle:
    handle.write("\n".join(report_lines))
