#!/usr/bin/env python3
import pandas as pd
import json
import datetime
import time


# Lread input
df1 = pd.read_table(snakemake.input.cutadapt)
df2 = pd.read_table(snakemake.input.dada2)
df2["total_retained"] = df2["total_retained"].apply(lambda x: f"{x}%")

# merge the  dataframe
df = pd.merge(df1, df2, on="sample")
new_columns = pd.MultiIndex.from_tuples([
    ("cutadapt", "reads retained"),
    ("cutadapt", "bps retained"),
    ("dada2", "reads.in"),
    ("dada2", "reads.out"),
    ("dada2", "dadaF"),
    ("dada2", "dadaR"),
    ("dada2", "merged"),
    ("dada2", "nonchim"),
    ("dada2", "total_retained"),
])
df_multi = df.set_index("sample")
df_multi.columns = new_columns

# read   parametri   Figaro
with open(snakemake.input.figaro_json, "r") as fh:
    data = json.load(fh)
d = data[0]
trim_position = f"forward:{d['trimPosition'][0]}, reverse:{d['trimPosition'][1]}"
max_expected_error = f"forward:{d['maxExpectedError'][0]}, reverse:{d['maxExpectedError'][1]}"

# tax info
tax_methods = {
    "decipher_silva138": ("DECIPHER", "Silva", "138"),
    "decipher_gtdb226": ("DECIPHER", "GTDB", "226"),
    "decipher_rdp18": ("DECIPHER", "RDP", "18"),
    "dada2_silva_genus138": ("DADA2", "Silva", "138"),
    "dada2_RDP_genus19": ("DADA2", "RDP", "19"),
    "dada2_GG2_genus09": ("DADA2", "GreenGenes2", "2024.09"),
    "dada2_RefSeq_RDPv16": ("DADA2", "RefSeq+RDP", "v16"),
    "dada2_GTDB_r202": ("DADA2", "GTDB", "r202"),
}

method, database, version = tax_methods.get(
    snakemake.params.taxonomy_method,
    ("Unknown", snakemake.params.taxonomy_method, "")
)

# ampwrap info
workflow_file = snakemake.params.workflow_file
version = snakemake.params.version


# build up report
start_formatted = datetime.datetime.fromisoformat(snakemake.params.start).strftime('%Y-%m-%d %H:%M:%S')
end_formatted = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

report = f"""
# Report file 
Analysis started: {start_formatted}
Analysis ended: {end_formatted}

## Primers
Forward: {snakemake.params.forward_p} 
Reverse: {snakemake.params.reverse_p}

## Figaro parameters
trim_position: {trim_position}
max_expected_error: {max_expected_error}

## Denoising stats:
{df_multi.to_string(index=True)}

## Taxonomy annotation
Method: {method}
Database: {database}
Version: {version}

## Ampwrap info
Workflow: {workflow_file}
Version: {version}

## Citation
generated by AmpWrap short
https://github.com/LDoni/AmpWrap
"""
with open(snakemake.output.report, "w") as f:
    f.write(report)
