{% set name = "ampwrap" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LDoni/AmpWrap/archive/v{{ version }}.tar.gz
  sha256: 3de65f3b0a720b14ffaf69795b657eb8bd261a24d175a31e29198d89a02e17ab

build:
  noarch: python
  number: 0
  script:
    - mkdir -p ${PREFIX}/bin/
    - cp ${SRC_DIR}/AmpWrap_long ${SRC_DIR}/AmpWrap_short ${PREFIX}/bin/
    - chmod +x ${PREFIX}/bin/AmpWrap_*
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ampwrap = ampwrap.cli:main
    - ampwrap-long = ampwrap.cli:long
    - ampwrap-short = ampwrap.cli:short

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - snakemake >=7.0
    - click >=8.0
    - cutadapt >=3.0
    - nanofilt
    - multiqc
    - fastqc >=0.11
    - porechop
    - porechop_abi
    - bioconda::bioconductor-dada2 >=1.20
    - bioconda::bioconductor-decipher >=2.20
    - emu
    - ca-certificates
    - openssl

test:
  commands:
    - ampwrap --help
    - ampwrap-long --help
    - ampwrap-short --help
    - pip check
  imports:
    - ampwrap

about:
  home: https://github.com/LDoni/AmpWrap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Comprehensive pipeline for amplicon sequence analysis'
  description: |
    AmpWrap provides automated processing of both short and long-read
    amplicon sequencing data through a Snakemake pipeline with quality
    control, trimming, and taxonomic classification.
  doc_url: https://github.com/LDoni/AmpWrap#readme
  dev_url: https://github.com/LDoni/AmpWrap

extra:
  recipe-maintainers:
    - LDoni
  channels:
    - conda-forge
    - bioconda
